#ifndef MEMORYLAYOUT_H
#define MEMORYLAYOUT_h

#define NUM_OF_PAGES 1024*128
#define PAGES_START_ADDR 0x100000
#define PAGE_SIZE 4096

//sizes in pages 
#define PAGE_DIRECTORY_START 0
#define PAGE_TABLES_START 1
#define PAGE_TABLE_COUNT 1024

#define USER_PAGES_START PAGE_TABLES_START + PAGE_TABLE_COUNT 
#define KERNEL_START_ADDR 0x6400000 //100 MB
#define KERNEL_SOURCE_SIZE 256 //1 MB 
#define KERNEL_STACK_START_ADDR KERNEL_START_ADDR + 0x100000 + PAGE_SIZE //kernel + 1MB + 4kB
#define KERNEL_STACK_SIZE 4


#define KERNEL_HEAP_SIZE 1024 * 3 


#endif